-- Migration 001 : champs artisan supplementaires
ALTER TABLE users ADD COLUMN IF NOT EXISTS civility TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS skills TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mobility TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS insurance TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS insurance_policy TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bank_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bank_account TEXT;
