version: '3.8'
services:
  web:
    build: ..
    container_name: fixpro_web
    restart: always
    environment:
      - FIXPRO_DB_HOST=db
      - FIXPRO_DB_USER=root
      - FIXPRO_DB_PASS=example
      - FIXPRO_DB_NAME=FixPro
      - PORT=8000
    ports:
      - "8000:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: fixpro_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: FixPro
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
